### ISSUE TITLE
TypeError: 'torch._C.Node' object is not subscriptable

### ISSUE THREAD

**Issue by nmnguyensg** [sukhitashvili/violence-detection#1]
Thank you for sharing this project. It is very helpful for me. But there is one problem I need your help.
When I run the file "run.py", I face the error in line model = Model(). The error is "TypeError: 'torch._C.Node' object is not subscriptable".
I dont know how to fix it. I hope you can help me giving the solution for it. Thank you a lot.

**Comment by nmnguyensg** [comment]
I have fixed it the problem. Thank you for sharing this project.

**Comment by sukhitashvili** [comment]
Hi, 
Glad you like the project.

Could you tell what was the solution?
